THISPWD=$(pwd)
XSL=$(mktemp -t FoXXXXXX)
TESTS=$(mktemp -t FoXXXXXX)
TMPFILE=$(mktemp -t FoXXXXXX)
TEST=$THISPWD/test.sh
ACTUALTEST=$THISPWD/actualtest.sh
XMLCONF=$THISPWD/xmlconf.xml
SAX_WELL_FORMED=$THISPWD/sax_well_formed
SAX_VALID=$THISPWD/sax_valid
DOM=$THISPWD/dom_canonicalize

PASSED=$THISPWD/PASSED.out
FAILED=$THISPWD/FAILED.out
LEAKED=$THISPWD/LEAKED.out
CRASHED=$THISPWD/CRASHED.out
NONASCII=$THISPWD/NONASCII
XFAIL=$THISPWD/XFAIL
XPASS=$THISPWD/XPASS.out
DIFF=$THISPWD/DIFF.out

export THISPWD XSL TESTS TMPFILE TEST ACTUALTEST XMLCONF SAX_WELL_FORMED SAX_VALID
export PASSED FAILED LEAKED CRASHED XFAIL XPASS NONASCII DIFF
