THISPWD=$(pwd)
XSL=$(mktemp -t FoX)
TESTS=$(mktemp -t FoX)
TMPFILE=$(mktemp -t FoX)
TEST=$THISPWD/test.sh
XMLCONF=$THISPWD/xmlconf.xml
SAX_WELL_FORMED=$THISPWD/sax_well_formed
SAX_VALID=$THISPWD/sax_valid

PASSED=$THISPWD/PASSED.out
FAILED=$THISPWD/FAILED.out
LEAKED=$THISPWD/LEAKED.out
CRASHED=$THISPWD/CRASHED.out
XFAIL=$THISPWD/XFAIL
XPASS=$THISPWD/XPASS.out

